### ISSUE TITLE
 Improve text "with variable" (searching a model)

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#254] opened 2020-02-04 19:15 UTC
![image](https://user-images.githubusercontent.com/2365990/73777182-e217a900-473d-11ea-8df2-a5278f4060b5.png)

**Comment by dgarijo** [comment] 2020-02-10 22:42
This issue is a duplicate of #270

**Closed** 2020-02-12 18:21 UTC
Labels: medium priority
