### ISSUE TITLE
[Model Catalog UI] Fix typo: requeriments to requirements

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-ui-lit#257] opened 2020-02-04 19:25 UTC
https://dev.mint.isi.edu/ethiopia/models/explore/HAND/HANDv1/hand_v1_simple/hand_v1_simple_ganale

**Comment by dgarijo** [comment] 2020-02-10 23:07
I cannot reproduce this issue, I will close it and we will reopen if necessary.

**Closed by dgarijo** 2020-02-10 23:07 UTC
